# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Chris Gascoigne
# tagline:          'A Jekyll theme'
description:      'cisco data centre architect / opinions are my own'
url:              http://blog.esquilax.org
baseurl:          /

author:
  name:           'Chris Gascoigne'
  url:            https://twitter.com/chrisgascoigne

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/cgascoig/cgascoig.github.io
